version: "3.9"
services:

  mongo:
    image: mongo:4.4.14
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  chrono_server:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

volumes:
  mongo-data: